### ISSUE TITLE
Problem Solved with Zoho Docs Cancel Request: Advice Request Endnote Creation from footnotes after Endnotes were originally created

### ISSUE THREAD

**Issue by ScottsContracting** [bennettscience/endnotes#1]
I created a google document and utilized the End Note plug in to create end notes instead of footnotes. (it worked as suggested I was a little shocked honestly not many of google plugins do as advertised)  I have since added information and more footnotes to the document.  I do not want to make a mistake and loose all the prior end notes but would like newly added the footnotes added as end notes.  

Can the end note generator do this without loosing prior end notes and incorporated the newly added footnotes?

Thank you to whomever responds with advice or suggestions.

Scotty

**Comment by ScottsContracting** [comment]
Since posting, I made a copy of the document and attempted to run the End Note Generator with zero success.  any suggestions will be appreciated.  Scotty

**Comment by ScottsContracting** [comment]
I got it figured out, cancel this request.  I used Zoho.com

**Comment by bennettscience** [comment]
This is a known issue. Will need to rework the method used for tracking the order of endnotes to make it happen.

**Comment by GenevieveGrabman** [comment]
Hello, would someone please explain how to use Zoho Docs Cancel Request to unmake endnotes once these were created, so that additional endnotes can be added? I presume the first step is to pay for Zoho Docs. And then? Thank you.
