### ISSUE TITLE
No 'run' option on menu

### ISSUE THREAD

**Issue by tamagotchithief** [bennettscience/endnotes#11]
What the title says. There is not a run option for me on the menu.

**Comment by bennettscience** [comment]
@tamagotchithief Is it greyed out? Or not showing anything at all? Did you allow access in the permission popup?

I would uninstall by using the "Manage AddOns" link in the AddOns menu and make sure you give it permission to run in the document.

**Comment by tamagotchithief** [comment]
Hello,

It was not present at all at the time. I closed out of the browser and
opened it back up and it showed up. Not sure what the issue was, but it got
fixed. Your add on helped me a lot with my research paper, thank you for
making it.

**Comment by bennettscience** [comment]
Glad to hear it's working and that it helped!
