### ISSUE TITLE
Endnotes says it is generating end notes, but it is not.

### ISSUE THREAD

**Issue by phillypowerresearch** [bennettscience/endnotes#12]
I've clicked generate and it says "all footnotes converted" but none have been converted. I have six footnotes.

**Comment by bennettscience** [comment]
I've tested and I can't replicate the problem. Can you share the document with me so I can look at it directly?

**Comment by jonathanstanley** [comment]
Thank you for building the tool.  When I click "generate" nothing happens.  Here is an example:
https://docs.google.com/document/d/1w5hixzC32TN-06Su2F55CSrIrzRnz1jOtIxxTJsGemY/edit?usp=sharing

**Comment by bennettscience** [comment]
I'm sorry you're having problems. I jumped into the doc you linked and I
was able to generate the endnotes. Can you try opening it fresh and running
it again? If you still have a problem, I'll hop back in and see if I can
narrow down a cause.

Brian E. Bennett
Web: ohheybrian.com
Twitter: @bennettscience <http://www.twitter.com/#!/bennettscience>
574.323.8519

**Comment by magnolia37** [comment]
> I've clicked generate and it says "all footnotes converted" but none have been converted. I have six footnotes.

I am having the same problem. I closed and re-opened my browser, which did not help.

**Comment by bennettscience** [comment]
@magnolia37 Can you share the document with me? You could also right click and choose **Inspect element** in the menu. Click on the **Console** tab at the top. Do you see any errors?

**Comment by magnolia37** [comment]
There seem to be three errors in the console tab:

/static/document/client/js/818081211-client_js_prod_kix_app.js:797 [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
dpd.tea @ /static/document/client/js/818081211-client_js_prod_kix_app.js:797
iframedAppPanel?eei=ACZUsOeBajDECOr9-rCy94N0q98mVjWU65J6R52lVDAruZvQlg51JsZaOLHLH7N-4JEJsRFfA93JApwErkZk5-_J48Oo9t42yPgoUSExnu0w90a2NHIX6VJX_Lmo58ygLzuQQi74xjX8c2q2OrmR2P037aKX41HTLMwc_QQrLaoQ1DWfVPh3LAg&mid=ACjPJvGZdBjSegjAimvIbeW-mbJE_up0RlD37T4TuD0ptiW-jwMctEAIcEkBx4t6bXbxclDvSH0uvcwOZuM5KyZKEffL0XWdHPrZnm4NsOm0bzEvxw&mid=ACjPJvEqwH4w6lyA9pz7NEhL5VIAJpmjpeQIwwAvwFIiBTsjXe-IiJSVNugIyBlek3FprRtMA2EDH6xsM9nVmpQPlKxqMIYCKzKzongYmfGWQ0JjNBB7hyoaLcdmHN7YsYid

vsRlaHQwgw:9 Unrecognized feature: 'vibrate'.

userCodeAppPanel:1 Unrecognized feature: 'vibrate'.

**Comment by magnolia37** [comment]
https://docs.google.com/document/d/1rxWwHrvOEi_Wmfeldb2Us8nQrgIuiMtfz6_9BqOZnz4/edit?usp=sharing

**Comment by bennettscience** [comment]
Those errors don't have anything to do with the addon. I made a copy of the document and ran the addon successfully. There was an extra page break at the end, so the endnotes were actually on page 5, not page 4.

Try opening the console and _then_ running the addon to see if anything is shown in red.

**Comment by darl99** [comment]
Hi I am having the same problem this document. Could you help? [https://docs.google.com/document/d/1QSYRsz3E65gVEDg2NTyVqu3kohCY0XHktcxCS9bqb9o/edit](url)

**Comment by bennettscience** [comment]
The doc you linked isn't public, so I can't try it.

Di you try following the instructions above? Run the addon and then right click the sidebar and choose **Inspect element** in the menu. Click on the **Console** tab at the top. Do you see any errors?

**Comment by magnolia37** [comment]
I ran it with the console open, and the only thing that popped up was the following:

1283047096-warden_bin_i18n_warden.js:197 Ro {message: "There was an error during the transport or process…this request. Error code = 10, Path = /wardeninit", name: "TransportError", stack: "TransportError: There was an error during the tran…/js/1283047096-warden_bin_i18n_warden.js:181:252)"}message: "There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit"name: "TransportError"stack: "TransportError: There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit↵    at new Ro (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:181:340)↵    at Wo.r.Bd (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:189:350)↵    at Hi (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:77:228)↵    at Gi (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:74:472)↵    at Bi.m (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:74:419)↵    at Hi (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:77:228)↵    at Gi (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:74:472)↵    at Wo.<anonymous> (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:188:159)↵    at Dn (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:146:304)↵    at Eo (https://docs.google.com/static/macros/client/js/1283047096-warden_bin_i18n_warden.js:181:252)"__proto__: Sbconstructor: ƒ Ro(a,b,c,d)__proto__: Error
1283047096-warden_bin_i18n_warden.js:57 Net state changed from IDLE to BUSY
1283047096-warden_bin_i18n_warden.js:57 Net state changed from BUSY to IDLE

**Comment by magnolia37** [comment]
I tried again and definitely did not get the endnotes on page 5. There are still only 4 pages. It seems the only difference is our computers ... 

Before the error message, there was a message that says:
iframedAppPanel:9 Unrecognized feature: 'vibrate'.
userCodeAppPanel:1 Unrecognized feature: 'vibrate'.

Could that be related?

**Comment by r0is** [comment]
Use Incognito Window, then try again. Maybe some extensions of your browser have conflicts with Endnotes.
