### ISSUE TITLE
Footnotes stay in when I run generator

### ISSUE THREAD

**Issue by jacobD1996** [bennettscience/endnotes#13]
I run the generator and it does add end notes however it does not take the footnotes out, what should I do?

**Comment by bennettscience** [comment]
I've tested and I can't replicate the problem. Is it possible to share the doc so I can look at it directly?

**Comment by jacobD1996** [comment]
​
 Group Paper
<https://docs.google.com/document/d/1dGiFXAK978MpQxJ-0Vo1d_2XVFnW1ngi7VdL0VLFUqY/edit?usp=drive_web>
​

**Comment by bennettscience** [comment]
@jacobD1996 Ok, I found the error. Two of your footnotes aren't actually footnotes, so the Addon is failing. Citations 6 and 7 have superscripts in _front_ of the text and the script expects the marker at the _end_ of the line.

All you need to do is delete 6 and 7 and reinsert them using Insert > Footnote. Then run the Addon again and it will convert everything.

[Here's a link to my copy](https://docs.google.com/document/d/1JeKXoqwNcoVaKzTFWtGIPlvWyKZPQUVOydEaHXe-DyI/edit?usp=sharing) with all footnotes converted. Reply here when you're finished and I'll close the issue.

**Comment by jacobD1996** [comment]
Gotcha, thanks oh the struggle of group projects with people that don't
know what they are doing haha.
