### ISSUE TITLE
Numbering endnotes from stratch again with every new chapter?

### ISSUE THREAD

**Issue by Francois34000** [bennettscience/endnotes#18]
Does Endnote Generator let you number your endnotes from 1 again with every new chapter in a single document? I'm afraid of converting all my (hundreds of) footnotes into endnotes for an entire book and then having no way to properly number the endnotes separately for each chapter.

**Comment by bennettscience** [comment]
Docs stores all footnotes in a large array. This drives creation of the endnotes. I would imagine it won't work the way you're hoping.

If you decide to try, please make a copy of the doc before running the addon.
