### ISSUE TITLE
G Suite Marketplace

### ISSUE THREAD

**Issue by liannepang** [bennettscience/endnotes#19]
Hello, your add-on is not showing up in G Suite Marketplace anymore. I was able to find it by doing a Google search, which took me to your page (https://dev.ohheybrian.com/endnotes/) and I could use the link there to install it. I work at a school and we recommend your generator to our students but it will be a lot harder for them to find if it's not in the Marketplace.

**Comment by bennettscience** [comment]
Thanks for the heads up! I started the migration but apparently never finished it this summer. You should now see it in the Marketplace.
