### ISSUE TITLE
"Run" does not appear

### ISSUE THREAD

**Issue by jorgeandr3s** [bennettscience/endnotes#2]
<a href="http://es.tinypic.com?ref=2dacc38" target="_blank"><img src="http://i67.tinypic.com/2dacc38.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by bennettscience** [comment]
Have you tried reloading the document? I can't get the problem to reproduce.

**Comment by jorgeandr3s** [comment]
It worked after I "turned off and on". Ugh. Sorry about that.

**Comment by bennettscience** [comment]
No worries.
