### ISSUE TITLE
After the End Notes are generated, there are not links between end notes and the "superscripts" that point to End Notes

### ISSUE THREAD

**Issue by liviudelureanu** [bennettscience/endnotes#20]
After the End Notes are generated, there are not generated links between End Notes and the "superscripts" that point to End Notes and also there are not links that point back, from End Notes to "superscripts". I think such a feature will be usefull.

**Comment by bennettscience** [comment]
Fixed in #25 

Watch for the automated update from the Workspace Marketplace.
