### ISSUE TITLE
Undo option

### ISSUE THREAD

**Issue by Avi5732** [bennettscience/endnotes#23]
I understand that one has to finish adding footnotes before generating the endnotes. But what happens if one makes a mistake, and has to add another note after all? Is there any way to undo the generation, add the missing note, and generate the endnotes again? Thanks!

**Comment by bennettscience** [comment]
You can either use the normal undo option (Edit menu > Undo or Ctrl/Cmd +
Z) or use the version history to go back to a version before endnotes were
added.
