### ISSUE TITLE
First citation number is default size instead of matching size of footnotes

### ISSUE THREAD

**Issue by AdriannaWenz** [bennettscience/endnotes#24]
I manually changed the fontsize of all footnotes from 11 (default for 'Normal text') to 8. When I generated endnotes, the first citation number was fontsize 11, matching default instead of fontsize of endnotes. All other endnotes and citation numbers were fontsize 8.
<img width="167" alt="Screen Shot 2020-11-22 at 7 38 22 AM" src="https://user-images.githubusercontent.com/20160721/99904000-36245780-2c96-11eb-84c8-075ad7f075d9.png">

**Comment by bennettscience** [comment]
I took some time to dig into this because it should be doable. But, when I try to capture the font size before creating the end note, there's no data there. I'm going to chalk this up to a bug with Google's resources and I'll keep an eye on it for later.

**Comment by bennettscience** [comment]
Added a bug report to the Apps Script team:

https://issuetracker.google.com/issues/182253589

**Comment by bennettscience** [comment]
@AdriannaWenz This has been fixed in the most recent addon version. You should see v.0.6.1 at the bottom of the siebar.

**Comment by bennettscience** [comment]
@AdriannaWenz This has been fixed in the most recent addon version. You should see v.0.6.1 at the bottom of the sidebar.
