### ISSUE TITLE
Anyway to revert to footnotes

### ISSUE THREAD

**Issue by jbrockw2** [bennettscience/endnotes#28]
I used this add-on after completing a project but I had to update it this year and I added new footnotes. Is there anyway I can revert to footnotes so the numbering all goes together?

**Comment by bennettscience** [comment]
Unfortunately, no. When the script converts to endnotes, the original footnote order is lost. The only way you'd be able to do it is to revert to a version just before you created the endnotes, insert your content, and then convert them all to endnotes again.
