### ISSUE TITLE
Can't reverse!!

### ISSUE THREAD

**Issue by LisaSchirch** [bennettscience/endnotes#36]
EndNote Generator is not reversible... and my fatal flaw of seeing what it would look like in my document to use endnotes instead of footnotes has  now caused me HOURS of work to hand enter all the footnotes again.

Even if I download the GoogleDoc to Word, I still cannot switch between endnotes and footnotes.

This is a horrible program and shouldn't be allowed to operate without this basic functionality of reversing back to footnotes.

**Comment by bennettscience** [comment]
The addon information says specifically that to go back, you have to restore a version using the Version History tool in the document. I'm sorry that you had that issue.
