### ISSUE TITLE
Add on doesn't work, script works fine however

### ISSUE THREAD

**Issue by MrMeerkat** [bennettscience/endnotes#4]
As the title says, just added the add on "Endnote Generator"  and the run button isn't showing up regardless of whether I refreshed the page or reopened the document on another device. It was added today so it should be the newest version(?). 
Wasn't the newest version supposed to fix this bug?  

Anyway, the script works fine so at least I got my endnotes :) 

(oh by the way, thank you)

**Comment by bennettscience** [comment]
Glad the script worked.

There is a really bizarre issue with Google not giving the correct permissions to the script, even though they're accounted for in the code. I did some reworking and haven't run into the issue with the newest version, so I'm going to close this for now. Thanks for using the program!
