### ISSUE TITLE
"No footnotes to convert"

### ISSUE THREAD

**Issue by RussellVWarren** [bennettscience/endnotes#5]
I found the text note that appears after you hit "Run" ("No footnotes to convert") to be a bit confusing, as it can be read as an error message ("there are no footnotes in the document to convert").  Maybe consider changing it to something like "Footnotes converted!"

This will be a very useful tool for the students I'm working with.  Thanks for your work in coding it and creating it as an Add-On (instead of just a script)!

**Comment by bennettscience** [comment]
Good suggestion. I'll make the change and publish it with some other improvements coming soon. Thanks!

**Comment by bennettscience** [comment]
Planned for next release.
